<?php
session_start();
$_SESSION['user_id'] = 1;

// Test the complete AI pipeline
echo "<h1>🤖 Testing Complete AI Pipeline</h1>\n";

// Test 1: Chat Response
echo "<h2>💬 Testing Chat Response</h2>\n";
$url = "http://localhost/budget/api/insights_data.php?action=chat_response&query=" . urlencode("what are my goals");
$response = file_get_contents($url);
$data = json_decode($response, true);

echo "<p><strong>Question:</strong> What are my goals?</p>\n";
echo "<p><strong>Response:</strong></p>\n";
echo "<div style='background: #f0f0f0; padding: 10px; margin: 10px 0; border-radius: 5px;'>\n";
if (isset($data['message'])) {
    echo nl2br(htmlspecialchars($data['message']));
} else {
    echo "Error: " . (isset($data['error']) ? $data['error'] : 'Unknown error');
    echo "<br>Raw response: " . htmlspecialchars($response);
}
echo "</div>\n";

// Test 2: Predictive Insights
echo "<h2>🔮 Testing Predictive Insights</h2>\n";
$url2 = "http://localhost/budget/api/insights_data.php?action=predictions";
$response2 = file_get_contents($url2);
$data2 = json_decode($response2, true);

echo "<p><strong>Generated Insights:</strong></p>\n";
echo "<div style='background: #f0f0f0; padding: 10px; margin: 10px 0; border-radius: 5px;'>\n";
if (isset($data2['insights'])) {
    foreach ($data2['insights'] as $insight) {
        echo "• " . htmlspecialchars($insight) . "<br>\n";
    }
    echo "<br><em>Generated by: " . ($data2['generated_by'] ?? 'unknown') . "</em>";
} else {
    echo "Error: " . (isset($data2['error']) ? $data2['error'] : 'Unknown error');
    echo "<br>Raw response: " . htmlspecialchars($response2);
}
echo "</div>\n";

echo "<h2>✅ AI Pipeline Test Complete!</h2>\n";
?>
